name: Build and Test .NET Projects

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  build-and-test:
    strategy:
      matrix:
        dotnet-version: ['6.x', '7.x', '8.x']  # Specify the desired versions

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Set up .NET Core for each version
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Restore and build the application
      - name: Restore and Build
        run: |
          dotnet restore
          dotnet build

      # Run tests using the existing restore
      - name: Run Tests
        run: dotnet test
